baseURL = "https://watercolor.whistler.page"
title = "WATERCOLOR.WHISTLER.PAGE"
languageCode = "en"
DefaultContentLanguage = "en" # Change this to change the site's language
theme = "hugo.386"
preserveTaxonomyNames = true
ignoreErrors = ["error-missing-instagram-accesstoken"]
enableEmoji = true

[params]
    # I fixed OpenGraph :D
    opengraph = true
    twittercards = true
    title = "WATERCOLOR.WHISTLER.PAGE"
    description = "Gateway Boot Error"
    images = ["setup.png"]
    
    # The name to display as main title in the home page
    mainpagetitle = "Gateway Boot Error"

    # The subtitle to display under the title in the home page
    mainpagesubtitle = "Gateway Boot Manager has experienced a problem." 

    # The description of your website. It will be displayed in the home page
    mainpagedesc = "Status: 0xc000000f. Info: An error occurred transferring execution. You can try to recover the system with the Systemware Gateway System Recovery Tools. (You might need to restart the system manually.) If the problem continues, please contact your system administrator or computer manufacturer."

    # Show the "built on Hugo" disclaimer
    showhugo = false

    # Show a CRT screen effect. Default is enabled.
    showcrt = true

    # Urls for social networks
    facebook = ""
    twitter = ""
    linkedin = ""
    github = ""
    gitlab = ""

    # Enables or disables the loading animations. false activates them. Default is false.
    fastload = true

    # Sets the speed for the page loading effect. Default is 1.0.
    loadspeedfactor = 1.0

    # Enables or disables the second flyby cursor. Default is false.
    loadonepass = false

[params.copyright]
    name = "wtrclr"

    # The url to use as link in the copyright name in the footer. Leave empty to use none.
    url = ""

    # Text to go before copyright information
    prefix = ""

    # Text to go between copyright and hugo disclaimer (if enabled)
    suffix = ""

[menu]
  # This displays buttons in the navbar to access your contents
  [[menu.main]]
    identifier = "about" # An unique identifier for the button
    name = "ABOUT"       # A display name for the button
    url = "/about/"      # The path to the content. It can lead to a single page (like here)
    weight = 10          # A number to order the buttons in the navbar

  [[menu.main]]
    identifier = "posts"
    name = "ALL_POSTS"
    url = "/post/"       # The path can lead to a content folder too.
    weight = 20

  [[menu.main]]
    identifier = "comms"
    name = "COMMS"
    url = "/comm/"       # The path can lead to a content folder too.
    weight = 30

[taxonomies]
category = "categories"
tag = "tags"


[privacy]

  [privacy.vimeo]
    disabled = true
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = true
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true
    